version: "3.8"

services:
  spigotmc-verification-bot:
    container_name: SpigotMCVerificationBot
    build: .
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config/config.yml:ro

x-remove-image: &remove-image
  remove_images: all